Story7/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import auth_logout
from auth9.views import loginUser, logoutUser, register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homePage.urls')),
    path('books', include('books.urls')),
    path('login', loginUser, name='login'),
    path('register', register, name='register'),
    path('logout', logoutUser, name='logout'),
    path('auth', include('auth9.urls'))
]

auth9/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', loginUser, name="login")
]

books/urls.py
from django.urls import path
from .views import book

app_name = 'books'

urlpatterns = [
    path('', book, name='books'),
]

homePage/urls.py
from django.urls import path
from .views import index

app_name = 'homePage'

urlpatterns = [
    path('', index, name='homepage'),
]

auth9/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.

homePage/models.py
from django.db import models

# Create your models here.

auth9/forms.py
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'user',
        'placeholder' : 'Enter your username here'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class' : 'form-control',
        'id' : 'passw',
        'placeholder' : 'Password'
    }))

auth9/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .forms import UserForm

# Create your views here.

def register(request):
    if (request.method == 'POST'):
        form = UserCreationForm(request.POST);
        username = request.POST['username'];
        password = request.POST['password1'];

        if (form.is_valid()):
            User.objects.create_user(username=username, password=password);
            return redirect('/')
    else:
        form= UserCreationForm()

    return render(request, 'register.html', {'form' : form})

def loginUser(request):
    if (request.method == 'POST'):
        form = UserForm(request.POST);
        username = request.POST['username'];
        password = request.POST['password'];
        user = authenticate(request, username=username, password=password);

        if (user is not None):
            login(request, user);
            request.session.set_expiry(300);
            return redirect('/')
        else:
            return redirect('/login')
    else:
        form = UserForm()

    return render(request, 'login.html', {'form':form})

def logoutUser(request):
    logout(request)
    return redirect(reverse(loginUser))

books/views.py
from django.shortcuts import render

# Create your views here.
def book(request):
    return render(request, 'book.html')

homePage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

auth9/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container section-container flex-center-col p-5">
    <h1 class="text-24 bold ">Log in</h1>
    <form method="POST" class="flex-center-col" action="{% url 'login' %}">
        {% csrf_token %}
        <div class="form-container mt-2" style="width: 200pt;">
            <label for="user" class="text-12">Username:</label>
            {{form.username}}
        </div>
        <div class="form-container mt-2" style="width: 200pt;">
            <label for="passw" class="text-12">Password:</label>
            {{form.password}}
        </div>
        <button class="btn btn-primary my-4 py-2 px-5" name="login" id="login">Login</button>
    </form>
    <div class="flex-center-col ">
        <p class="text-18 m-0">Don't have one? Join today</p>
        <a href="{% url 'register' %}" class="text-12">Sign Up</a>
    </div>
</div>
{% endblock %}

auth9/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container section-container flex-center-col p-5">
    <h1 class="text-24 bold ">Create your account</h1>
    <form method="POST" class="flex-center-col" action="{% url 'register' %}">
        {% csrf_token %}
        <div class="form-container mt-2">
            {{form}}
        </div>
        <button class="btn btn-primary my-4 py-2 px-5">Sign up</button>
    </form>
    <div class="flex-center-col ">
        <p class="text-18 m-0">Already have one?</p>
        <a href="{% url 'register' %}" class="text-12">Sign in</a>
    </div>
</div>
{% endblock %}

books/templates/book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mb-5 mx-5 py-2 flex-center-col align-c">
    <h1 class="text-36 mb-3">Book Finder</h1>
    <form class="form-inline mb-2">
        <input class="form-control searchbox " type="search" placeholder="Search" aria-label="Search">
        <div class="append flex">
            <input class="form-control mr-sm-2 mr-2 numbox" min="1" max="20" placeholder="10" id="custom1" type="number">
        </div>
        <button class="btn btn-outline-primary my-2 my-sm-0 btn-search" type="submit">Search</button>
    </form>
    <div class="spinner-border text-secondary none" role="status" style="padding: 20px; margin: 20px;">
            <span class="sr-only">Loading...</span>
          </div>
</div>

    <div class="result align-l mx-5">
        <div class="status-container none">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Writer</th>
                        <th scope="col">Pages</th>
                        <th scope="col">Publisher</th>
                        <th scope="col">Categories</th>
                        <th scope="col">Cover</th>
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
            </table>
        </div>
        <p class="text-center">Nothing to show</p>
    </div>

{% endblock %}

homePage/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Brian | Story 7</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #ffffff00;">
          <p class="navbar-brand mb-0 text-navbar">BRATYU</p>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homePage:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'books:books' %}">Book Finder</a>
                </li>
              </ul>
              

              <div class="flex-left py-2 ml-auto">
                  {% if user.is_authenticated %}          
                  <a href= "{% url 'logout' %}" class="btn btn-primary py-2 px-4" style="margin-right: 20px;">Sign out</a>
                  {% else %}
                  <a href="{% url 'login' %}" class="btn btn-primary py-2 px-4" style="margin-right: 20px;">Sign in</a>
                  {% endif %}
                  <label class='switch mr-3'>
                    <input type='checkbox' id="toggle">
                    <span class="slider round"></span>
                  </label>
                  <p class="mb-2 text-12">Dark Mode</p>
              </div>
            </div>
          
      
      </nav>

      {% block content %}
    {% endblock content %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'books.js' %}"></script>
  </body>
</html>

homePage/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="mb-5 mx-5 py-2 flex-center-col align-c">   
        <p class="bold text-24 align-c" style="margin: 20px;">
            Hello {% if user.is_authenticated %}  {{ user.get_username }} {% endif %}
        </p>
        <img src="{% static 'img/IMG_0834.jpg' %}" alt="me" class="align-c" id="foto">
        <p class="bold text-24 align-c" style="margin: 20px;">Brian Athallah Yudiva</p>
        <p class="desc align-c">Hi! I'm Brian, a Computer Science student in Fasilkom UI</p>
    </div>

        <div class="accordion">
            <div>
                <p class="title text-light ac-i bg-dark">Aktivitas</p>
                <div class="desc">
                    <ul>
                        <li>Fotografi</li>
                        <li>Videografi</li>
                        <li>Ngoding</li>
                    </ul>
                </div>
            </div>

            <div>
                <p class="title text-light ac-i bg-dark">Organisasi & Kepanitiaan</p>
                <div class="desc">
                    <ul>
                        <li>PIC Documentation & Cinematic PERAK 2020</li>
                        <li>VPIC Documentation PMB 2019</li>
                        <li>Staff of Seminar COMPFEST 11</li>
                        <li>Staff of LO Open House Fasilkom 2019</li>
                        <li>Staff of Documentation EduCare 2019</li>
                        <li>Staff of Equipment CGT 2019</li>
                    </ul>
                </div>
            </div>

            <div>
                <p class="title text-light ac-i bg-dark">Prestasi</p>
                <div class="desc">
                    <ul>
                        <li>Coming Soon...</li>
                    </ul>
                </div>
        
        </div>
        </div>

        <p class="bold text-24 align-c" style="margin: 20px;">Contact Me</p>
        <div class="mb-5 mx-5 py-2 flex-center-col align-c">

        <div class="flex-left mb-5">
            <div id="instagram" class="mx-3">
                <a href="https://www.instagram.com/brianyudiva"><svg class="icon24" viewBox="0 0 169.063 169.063"
                        style="enable-background:new 0 0 169.063 169.063;">
                        <g>
                            <path d="M122.406,0H46.654C20.929,0,0,20.93,0,46.655v75.752c0,25.726,20.929,46.655,46.654,46.655h75.752
                                c25.727,0,46.656-20.93,46.656-46.655V46.655C169.063,20.93,148.133,0,122.406,0z M154.063,122.407
                                c0,17.455-14.201,31.655-31.656,31.655H46.654C29.2,154.063,15,139.862,15,122.407V46.655C15,29.201,29.2,15,46.654,15h75.752
                                c17.455,0,31.656,14.201,31.656,31.655V122.407z" />
                            <path
                                d="M84.531,40.97c-24.021,0-43.563,19.542-43.563,43.563c0,24.02,19.542,43.561,43.563,43.561s43.563-19.541,43.563-43.561
                                C128.094,60.512,108.552,40.97,84.531,40.97z M84.531,113.093c-15.749,0-28.563-12.812-28.563-28.561
                                c0-15.75,12.813-28.563,28.563-28.563s28.563,12.813,28.563,28.563C113.094,100.281,100.28,113.093,84.531,113.093z" />
                            <path d="M129.921,28.251c-2.89,0-5.729,1.17-7.77,3.22c-2.051,2.04-3.23,4.88-3.23,7.78c0,2.891,1.18,5.73,3.23,7.78
                                c2.04,2.04,4.88,3.22,7.77,3.22c2.9,0,5.73-1.18,7.78-3.22c2.05-2.05,3.22-4.89,3.22-7.78c0-2.9-1.17-5.74-3.22-7.78
                                C135.661,29.421,132.821,28.251,129.921,28.251z" />
                        </g>
                    </svg>
                </a>
            </div>
            <div id="in" class="mx-3"><a href="https://www.linkedin.com/in/brian-athallah-y-b81869114/">
                    <svg class="icon24" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 310"
                        style="enable-background:new 0 0 310 310;">
                        <g id="XMLID_801_">
                            <path id="XMLID_802_" d="M72.16,99.73H9.927c-2.762,0-5,2.239-5,5v199.928c0,2.762,2.238,5,5,5H72.16c2.762,0,5-2.238,5-5V104.73
                        C77.16,101.969,74.922,99.73,72.16,99.73z" />
                            <path id="XMLID_803_" d="M41.066,0.341C18.422,0.341,0,18.743,0,41.362C0,63.991,18.422,82.4,41.066,82.4
                        c22.626,0,41.033-18.41,41.033-41.038C82.1,18.743,63.692,0.341,41.066,0.341z" />
                            <path id="XMLID_804_" d="M230.454,94.761c-24.995,0-43.472,10.745-54.679,22.954V104.73c0-2.761-2.238-5-5-5h-59.599
                        c-2.762,0-5,2.239-5,5v199.928c0,2.762,2.238,5,5,5h62.097c2.762,0,5-2.238,5-5v-98.918c0-33.333,9.054-46.319,32.29-46.319
                        c25.306,0,27.317,20.818,27.317,48.034v97.204c0,2.762,2.238,5,5,5H305c2.762,0,5-2.238,5-5V194.995
                        C310,145.43,300.549,94.761,230.454,94.761z" />
                        </g>
                    </svg>
                </a>
            </div>
            <div id="twitter" class="mx-3"><a href="https://twitter.com/brianyudiva">
                    <svg class="icon24" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;">
                        <g>
                            <path d="M512,97.248c-19.04,8.352-39.328,13.888-60.48,16.576c21.76-12.992,38.368-33.408,46.176-58.016
                            c-20.288,12.096-42.688,20.64-66.56,25.408C411.872,60.704,384.416,48,354.464,48c-58.112,0-104.896,47.168-104.896,104.992
                            c0,8.32,0.704,16.32,2.432,23.936c-87.264-4.256-164.48-46.08-216.352-109.792c-9.056,15.712-14.368,33.696-14.368,53.056
                            c0,36.352,18.72,68.576,46.624,87.232c-16.864-0.32-33.408-5.216-47.424-12.928c0,0.32,0,0.736,0,1.152
                            c0,51.008,36.384,93.376,84.096,103.136c-8.544,2.336-17.856,3.456-27.52,3.456c-6.72,0-13.504-0.384-19.872-1.792
                            c13.6,41.568,52.192,72.128,98.08,73.12c-35.712,27.936-81.056,44.768-130.144,44.768c-8.608,0-16.864-0.384-25.12-1.44
                            C46.496,446.88,101.6,464,161.024,464c193.152,0,298.752-160,298.752-298.688c0-4.64-0.16-9.12-0.384-13.568
                            C480.224,136.96,497.728,118.496,512,97.248z" />
                        </g>
                    </svg>
                </a>
            </div>
            <div id="facebook" class="mx-3"><a href="https://www.facebook.com/brianathallah.yudiva">
                    <svg class="icon24" viewBox="0 0 470.513 470.513"
                        style="enable-background:new 0 0 470.513 470.513;">
                        <g>
                            <path
                                d="M271.521,154.17v-40.541c0-6.086,0.28-10.8,0.849-14.13c0.567-3.335,1.857-6.615,3.859-9.853
                        c1.999-3.236,5.236-5.47,9.706-6.708c4.476-1.24,10.424-1.858,17.85-1.858h40.539V0h-64.809c-37.5,0-64.433,8.897-80.803,26.691
                        c-16.368,17.798-24.551,44.014-24.551,78.658v48.82h-48.542v81.086h48.539v235.256h97.362V235.256h64.805l8.566-81.086H271.521z" />
                        </g>
                    </svg>
                </a>
            </div>
        </div>
        </div>

    
</div>
{% endblock %}